### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by WickedSchnitzel** [Wiltoga/VS-OfflineFoodNoSpoil#1]
```
[Error] Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Common.InventoryPlayerCreative.get_Count() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Common\GameContent\Inventory\InventoryPlayerCreative.cs:line 227
   at Vintagestory.API.Common.InventoryBase.GetEnumerator()+MoveNext() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Common\Inventory\InventoryBase.cs:line 862
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at Wiltoga.OfflineFoodNoSpoil.Event_PlayerDisconnect(IServerPlayer byPlayer) in C:\Users\natha\source\repos\VS-OfflineFoodNoSpoil\OfflineFoodNoSpoil\OfflineFoodNoSpoil.cs:line 46
   at Vintagestory.Server.ServerEventManager.TriggerPlayerDisconnect(IServerPlayer player) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\ServerEventManager.cs:line 617
```

**Comment by Wiltoga** [comment]
Any step to reproduce the crash ?

**Comment by Wiltoga** [comment]
Ok should be fixed, the player inventories included any other inventory beside hotbar & backpacks (so for example the creative menu). If you want to test it before I release it : [OfflineFoodNoSpoil_1.0.2.zip](https://github.com/Wiltoga/VS-OfflineFoodNoSpoil/files/12865975/OfflineFoodNoSpoil_1.0.2.zip) (goes into `%appdata%\VintagestoryData\Mods`, remove the old version)
